/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Control.Conexion;
import Control.MyiReportVisor;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.HashMap;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gaby
 */
public final class ComprasxProveedor extends javax.swing.JFrame {
    DefaultTableModel model;
    Connection con = new Conexion().conectar();
    HashMap parametros = new HashMap();
    MyiReportVisor mrv;
    public ComprasxProveedor() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/IMG/icoono.jpg")).getImage());
        setLocationRelativeTo(null);
        btn_reporte.setEnabled(false);
        cargarProveedores();
    }
    
    
    public void cargarProveedores(){
        String titulo[] = {"ID","NOMBRE","RUC","TELEFONO","DIRECCION","EMAIL"};
        model = new DefaultTableModel(null, titulo);
        tbl_proveedores.setModel(model);
        String datos[] = new String[6];
        String sql ="SELECT `id_provee`, `nom_provee`, `ruc_provee`, `telf_provee`, `dir_provee`, `email_provee` FROM tproveedor";
        try {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                datos[0] = rs.getString("id_provee");
                datos[1] = rs.getString("nom_provee");
                datos[2] = rs.getString("ruc_provee");
                datos[3] = rs.getString("telf_provee");
                datos[4] = rs.getString("dir_provee");
                datos[5] = rs.getString("email_provee");
                model.addRow(datos);
            }
            tbl_proveedores.setModel(model);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
    
    public void generarPDF(int id){
        String titulo[] = {"ID","NOMBRE","RUC","TELEFONO","DIRECCION","EMAIL"};
        model = new DefaultTableModel(null, titulo);
        tbl_proveedores.setModel(model);
        String datos[] = new String[6];
        String sql ="SELECT `id_provee`, `nom_provee`, `ruc_provee`, `telf_provee`, `dir_provee`, `email_provee` FROM tproveedor";
        try {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                datos[0] = rs.getString("id_provee");
                datos[1] = rs.getString("nom_provee");
                datos[2] = rs.getString("ruc_provee");
                datos[3] = rs.getString("telf_provee");
                datos[4] = rs.getString("dir_provee");
                datos[5] = rs.getString("email_provee");
                model.addRow(datos);
            }
            tbl_proveedores.setModel(model);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btn_reporte = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_proveedores = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 102, 255), 2, true));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("CLIC EN \"VER REPORTE\" PARA VISUALIZAR LAS COMPRAS REALIZADAS");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, -1, -1));

        btn_reporte.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btn_reporte.setText("VER REPORTE");
        btn_reporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reporteActionPerformed(evt);
            }
        });
        jPanel1.add(btn_reporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, -1, -1));

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("SELECCION DE PROVEEDOR");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        tbl_proveedores.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        tbl_proveedores.setForeground(new java.awt.Color(0, 51, 255));
        tbl_proveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_proveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_proveedoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_proveedores);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 700, 290));

        jPanel2.setBackground(new java.awt.Color(0, 102, 255));
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 730, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 730, 500));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Banner.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_reporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reporteActionPerformed
        int fila = tbl_proveedores.getSelectedRow();
        int idcompra = Integer.parseInt(tbl_proveedores.getValueAt(fila, 0).toString());
        String nomProveedor = tbl_proveedores.getValueAt(fila, 1).toString();
        parametros.put("nombre",nomProveedor);
        parametros.put("id_compra", idcompra);
        mrv = new MyiReportVisor(System.getProperty("user.dir")+"\\reportes\\reportexProveedor.jrxml", parametros);
        mrv.exportarAPdf();
    }//GEN-LAST:event_btn_reporteActionPerformed

    private void tbl_proveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_proveedoresMouseClicked
            int fila = tbl_proveedores.getSelectedRow();
        if (fila != -1) {
           btn_reporte.setEnabled(true);

        }
    }//GEN-LAST:event_tbl_proveedoresMouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        int fila = tbl_proveedores.getSelectedRow();
        if (fila != -1) {
            btn_reporte.setEnabled(false);

        }
    }//GEN-LAST:event_jPanel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComprasxProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComprasxProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComprasxProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComprasxProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComprasxProveedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_reporte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_proveedores;
    // End of variables declaration//GEN-END:variables
}
