/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Control.Conexion;
import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Time;
import javax.swing.JOptionPane;

/**
 *
 * @author Gaby
 */
public final class Configuracion extends javax.swing.JFrame {

    Connection con = new Conexion().conectar();
    int posx, posy;
    
    public Configuracion() {
        setUndecorated(true);
        setAlwaysOnTop(true);
        initComponents();
        this.getContentPane().setBackground(Color.WHITE);
        setLocationRelativeTo(null);
        btn_actualizar_empresa.setEnabled(false);
        lbl_fecha.setText(""+new Fechas().fechaCadena());
        int mm = getMaxId();
        cargar(mm);
    }
    
    
    public void cargar(int id){
        String sql = "SELECT `nom_empresa`, `dir_empresa`, `telf_empresa`, `ruc_empresa`, `nom_responsable_empresa`, `igv`, `cambio`, `anuncio`, `ingreso`, `salida`, `id_usu`,`salario` FROM `tconfiguracion` WHERE id_config = "+id+" ";
        try {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            String datos[] = new String[11];
            if (rs.next()) {
                datos[0] = rs.getString("nom_empresa");
                datos[1] = rs.getString("dir_empresa");
                datos[2] = rs.getString("telf_empresa");
                datos[3] = rs.getString("ruc_empresa");
                datos[4] = rs.getString("nom_responsable_empresa");
                datos[5] = rs.getString("cambio");
                datos[6] = rs.getString("igv");
                datos[7] = rs.getString("anuncio");
                datos[8] = rs.getString("ingreso");
                datos[9] = rs.getString("salida");
                datos[10] = rs.getString("salario");
                
                 txt_nom.setText(datos[0]);
                 txt_direccion.setText(datos[1]);
                 txt_telefono.setText(datos[2]);
                 txt_ruc.setText(datos[3]);
                 txt_responsable.setText(datos[4]);
                 txt_cambio.setText(datos[5]);
                 txt_igv.setText(datos[6]);
                 txa_anuncios.setText(datos[7]);
                 txt_entrada.setText(datos[8]);
                 txt_salida.setText(datos[9]);
                 txt_pago_minimo.setText(datos[10]);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(getRootPane(), e.getMessage());
        }
    }
    
    public int getMaxId(){
        int id = -1;
        String sql = "SELECT MAX(`id_config`) FROM `tconfiguracion`";
        try {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            if (rs.next()) {
                id = rs.getInt("MAX(`id_config`)");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(getRootPane(), e.getMessage());
        }
        return id;
    }
    
    
    public void bloquear(){
        btn_actualizar_empresa.setEnabled(false);
        txt_nom.setEnabled(false);
        txt_direccion.setEnabled(false);
        txt_telefono.setEnabled(false);
        txt_ruc.setEnabled(false);
        txt_responsable.setEnabled(false);
    }
    
    public void desbloquear(){
        btn_actualizar_empresa.setEnabled(true);
        txt_nom.setEnabled(true);
        txt_direccion.setEnabled(true);
        txt_telefono.setEnabled(true);
        txt_ruc.setEnabled(true);
        txt_responsable.setEnabled(true);
        txt_nom.requestFocus();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lbl_fecha = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_responsable = new javax.swing.JTextField();
        txt_nom = new javax.swing.JTextField();
        txt_direccion = new javax.swing.JTextField();
        txt_telefono = new javax.swing.JTextField();
        txt_ruc = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        btn_actualizar_cambio = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        txt_cambio = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        btn_actualizar_igv = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        txt_igv = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txa_anuncios = new javax.swing.JTextArea();
        btn_actualizar_anuncio = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btn_guardar_horarios = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txt_entrada = new javax.swing.JTextField();
        txt_salida = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btn_guardar_pagos = new javax.swing.JButton();
        txt_pago_minimo = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btn_actualizar_empresa = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel33 = new javax.swing.JLabel();
        chx_modificar = new javax.swing.JCheckBox();
        jPanel8 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/logout.png"))); // NOI18N
        jLabel10.setText("SALIR");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Banner.png"))); // NOI18N
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 60));

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("RESPONSABLE");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 680, 10));

        lbl_fecha.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lbl_fecha.setForeground(new java.awt.Color(0, 0, 102));
        lbl_fecha.setText("Viernes, 24 de Diciembre del 2015");
        getContentPane().add(lbl_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 200, -1));

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setText("NOMBRE");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 102));
        jLabel6.setText("DIRECCIÓN");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 102));
        jLabel7.setText("TELÉFONO");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 102));
        jLabel8.setText("RUC");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        txt_responsable.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txt_responsable.setForeground(new java.awt.Color(0, 51, 255));
        txt_responsable.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_responsable.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 1, true));
        txt_responsable.setEnabled(false);
        getContentPane().add(txt_responsable, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 220, -1));

        txt_nom.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txt_nom.setForeground(new java.awt.Color(0, 51, 255));
        txt_nom.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_nom.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 1, true));
        txt_nom.setEnabled(false);
        getContentPane().add(txt_nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 220, -1));

        txt_direccion.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txt_direccion.setForeground(new java.awt.Color(0, 51, 255));
        txt_direccion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_direccion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 1, true));
        txt_direccion.setEnabled(false);
        getContentPane().add(txt_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 220, -1));

        txt_telefono.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txt_telefono.setForeground(new java.awt.Color(0, 51, 255));
        txt_telefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_telefono.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 1, true));
        txt_telefono.setEnabled(false);
        txt_telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_telefonoKeyTyped(evt);
            }
        });
        getContentPane().add(txt_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 220, -1));

        txt_ruc.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txt_ruc.setForeground(new java.awt.Color(0, 51, 255));
        txt_ruc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_ruc.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 1, true));
        txt_ruc.setEnabled(false);
        txt_ruc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_rucKeyTyped(evt);
            }
        });
        getContentPane().add(txt_ruc, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 220, -1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 680, 10));

        jSeparator4.setBackground(new java.awt.Color(0, 102, 255));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 582, 680, 0));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 255), 1, true));
        jTabbedPane1.setForeground(new java.awt.Color(0, 0, 102));
        jTabbedPane1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 102));
        jLabel14.setText("CONFIGURAR CAMBIO DE DOLAR");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        btn_actualizar_cambio.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btn_actualizar_cambio.setText("GUARDAR");
        btn_actualizar_cambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizar_cambioActionPerformed(evt);
            }
        });
        jPanel5.add(btn_actualizar_cambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 230, -1));

        jLabel22.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 102));
        jLabel22.setText("CAMBIO HOY");
        jPanel5.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, -1));

        txt_cambio.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txt_cambio.setForeground(new java.awt.Color(0, 51, 255));
        txt_cambio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_cambio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 1, true));
        txt_cambio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cambioKeyTyped(evt);
            }
        });
        jPanel5.add(txt_cambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 90, -1));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cambio.png"))); // NOI18N
        jPanel5.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 130, 140));
        jPanel5.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 680, 20));

        jTabbedPane1.addTab("CAMBIO", jPanel5);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 102));
        jLabel13.setText("CONFIGURAR IMPUESTO GENERAL A LAS VENTAS");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        btn_actualizar_igv.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btn_actualizar_igv.setText("GUARDAR");
        btn_actualizar_igv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizar_igvActionPerformed(evt);
            }
        });
        jPanel4.add(btn_actualizar_igv, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 230, -1));

        jLabel21.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 102));
        jLabel21.setText("% IGV");
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        txt_igv.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txt_igv.setForeground(new java.awt.Color(0, 51, 255));
        txt_igv.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_igv.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 1, true));
        txt_igv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_igvKeyTyped(evt);
            }
        });
        jPanel4.add(txt_igv, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 90, -1));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cash-register-128.png"))); // NOI18N
        jPanel4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 130, 140));

        jTabbedPane1.addTab("IMPUESTOS", jPanel4);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txa_anuncios.setColumns(20);
        txa_anuncios.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txa_anuncios.setRows(5);
        txa_anuncios.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 102), 1, true));
        jScrollPane1.setViewportView(txa_anuncios);

        jPanel6.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 610, 100));

        btn_actualizar_anuncio.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btn_actualizar_anuncio.setText("GUARDAR");
        btn_actualizar_anuncio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizar_anuncioActionPerformed(evt);
            }
        });
        jPanel6.add(btn_actualizar_anuncio, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 230, -1));

        jLabel31.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 0, 102));
        jLabel31.setText("CONFIGURAR ANUNCIOS PARA EL PERSONAL");
        jPanel6.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jTabbedPane1.addTab("ANUNCIOS", jPanel6);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 102));
        jLabel11.setText("CONFIGURAR HORARIOS");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        btn_guardar_horarios.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btn_guardar_horarios.setText("GUARDAR");
        btn_guardar_horarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardar_horariosActionPerformed(evt);
            }
        });
        jPanel2.add(btn_guardar_horarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 230, -1));

        jLabel17.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 102));
        jLabel17.setText("ENTRADA");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, -1));

        jLabel18.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 102));
        jLabel18.setText("SALIDA");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, -1));

        txt_entrada.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txt_entrada.setForeground(new java.awt.Color(0, 51, 255));
        txt_entrada.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_entrada.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 1, true));
        txt_entrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_entradaKeyTyped(evt);
            }
        });
        jPanel2.add(txt_entrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 100, -1));

        txt_salida.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txt_salida.setForeground(new java.awt.Color(0, 51, 255));
        txt_salida.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_salida.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 1, true));
        txt_salida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_salidaKeyTyped(evt);
            }
        });
        jPanel2.add(txt_salida, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 100, -1));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boleta.png"))); // NOI18N
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 130, 140));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("* Respertar el formato de hora para no generar errores");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 102));
        jLabel9.setText("hh:MM:ss");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, -1, -1));

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 102));
        jLabel12.setText("hh:MM:ss");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, -1, -1));

        jTabbedPane1.addTab("HORARIOS", jPanel2);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setText("CONFIGURAR PAGOS PERSONAL");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        btn_guardar_pagos.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btn_guardar_pagos.setText("GUARDAR");
        btn_guardar_pagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardar_pagosActionPerformed(evt);
            }
        });
        jPanel1.add(btn_guardar_pagos, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 230, -1));

        txt_pago_minimo.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txt_pago_minimo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_pago_minimo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 1, true));
        txt_pago_minimo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_pago_minimoKeyTyped(evt);
            }
        });
        jPanel1.add(txt_pago_minimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 90, 20));

        jLabel15.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 102));
        jLabel15.setText("MINIMO VITAL");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/factura (1).png"))); // NOI18N
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 130, 140));

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel16.setText("S/.");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, -1));

        jTabbedPane1.addTab("PAGOS", jPanel1);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 680, 250));

        btn_actualizar_empresa.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btn_actualizar_empresa.setText("GUARDAR");
        btn_actualizar_empresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizar_empresaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_actualizar_empresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, 230, -1));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/farmacia.png"))); // NOI18N
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 130, 140));

        jLabel29.setBackground(new java.awt.Color(0, 0, 102));
        jLabel29.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 102));
        jLabel29.setText("EMPRESA");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 680, 10));

        jLabel33.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 0, 102));
        jLabel33.setText("EMPRESA");
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        chx_modificar.setBackground(new java.awt.Color(255, 255, 255));
        chx_modificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        chx_modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/modificar.png"))); // NOI18N
        chx_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chx_modificarActionPerformed(evt);
            }
        });
        getContentPane().add(chx_modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, -1, -1));

        jPanel8.setBackground(new java.awt.Color(0, 51, 255));
        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 680, 20));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 255), 2, true));
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 680, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void chx_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chx_modificarActionPerformed
        
        if (chx_modificar.isSelected()) {
            desbloquear();
        } else {
            bloquear();
        }
        
        
    }//GEN-LAST:event_chx_modificarActionPerformed

    private void btn_actualizar_empresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizar_empresaActionPerformed
        String nombre, dir, responsable,sql;
        int telf, ruc;        
        
        nombre = txt_nom.getText();
        dir = txt_direccion.getText();
        telf = Integer.parseInt(txt_telefono.getText());
        ruc = Integer.parseInt(txt_ruc.getText());
        responsable = txt_responsable.getText();
        
        sql = "UPDATE `tconfiguracion` SET `nom_empresa`= '"+nombre+"' ,`dir_empresa`= '"+dir+"' ,`telf_empresa`= "+telf+" ,`ruc_empresa`= "+ruc+" ,`nom_responsable_empresa`= '"+responsable+"' ";
        try {
            Statement st = con.createStatement();
            int res = st.executeUpdate(sql);
            if (res>0) {
                JOptionPane.showMessageDialog(getRootPane(), "Datos actualizados");
                bloquear();
            }
        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(getRootPane(), e.getMessage());        
        }
    }//GEN-LAST:event_btn_actualizar_empresaActionPerformed

    private void btn_actualizar_cambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizar_cambioActionPerformed
        double cambio = Double.parseDouble(txt_cambio.getText());
        String sql = "UPDATE `tconfiguracion` SET `cambio`= "+cambio+" ";
        try {
            Statement st = con.createStatement();
            int res = st.executeUpdate(sql);
            if (res>0) {
                JOptionPane.showMessageDialog(getRootPane(), "Cambio del dia actualizado");
            }
        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(getRootPane(), e.getMessage());        
        }
    }//GEN-LAST:event_btn_actualizar_cambioActionPerformed

    private void btn_actualizar_igvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizar_igvActionPerformed
        double igv = Double.parseDouble(txt_igv.getText());
        String sql = "UPDATE `tconfiguracion` SET `igv`= "+igv+" ";
        try {
            Statement st = con.createStatement();
            int res = st.executeUpdate(sql);
            if (res>0) {
                JOptionPane.showMessageDialog(getRootPane(), "Igv actualizado");
            }
        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(getRootPane(), e.getMessage());        
        }
    }//GEN-LAST:event_btn_actualizar_igvActionPerformed

    private void btn_actualizar_anuncioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizar_anuncioActionPerformed
        String msg = txa_anuncios.getText();
        String sql = "UPDATE `tconfiguracion` SET `anuncio`= '"+msg+"' ";
        try {
            Statement st = con.createStatement();
            int res = st.executeUpdate(sql);
            if (res>0) {
                JOptionPane.showMessageDialog(getRootPane(), "Anuncio actualizado");
            }
        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(getRootPane(), e.getMessage());        
        }
    }//GEN-LAST:event_btn_actualizar_anuncioActionPerformed

    private void btn_guardar_horariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardar_horariosActionPerformed
        if (!txt_entrada.getText().trim().isEmpty()) {
            if (!txt_salida.getText().trim().isEmpty()) {
                Time ingreso = Time.valueOf(txt_entrada.getText());
                Time salida = Time.valueOf(txt_salida.getText());
                String sql = "UPDATE `tconfiguracion` SET `ingreso`= '" + ingreso + "' ,`salida`= '" + salida + "' ";
                try {
                    Statement st = con.createStatement();
                    int res = st.executeUpdate(sql);
                    if (res > 0) {
                        JOptionPane.showMessageDialog(getRootPane(), "Horario actualizado");
                    }
                } catch (SQLException | HeadlessException e) {
                    JOptionPane.showMessageDialog(getRootPane(), e.getMessage());
                }
            } else {
                JOptionPane.showMessageDialog(getRootPane(), "Ingrese hora de salida");
                txt_salida.requestFocus();
            }
        } else {
            JOptionPane.showMessageDialog(getRootPane(), "Ingrese hora de entrada");
            txt_entrada.requestFocus();
        }
    }//GEN-LAST:event_btn_guardar_horariosActionPerformed

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        posx = evt.getX();
        posy = evt.getY();
    }//GEN-LAST:event_jLabel1MousePressed

    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
        Point point = MouseInfo.getPointerInfo().getLocation();
        this.setLocation(point.x-posx, point.y-posy);
    }//GEN-LAST:event_jLabel1MouseDragged

    private void btn_guardar_pagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardar_pagosActionPerformed
        if (!txt_pago_minimo.getText().trim().isEmpty()) {
            double salario = Double.parseDouble(txt_pago_minimo.getText());
            String sql = "UPDATE `tconfiguracion` SET `salario`= '" + salario + "' ";
            try {
                Statement st = con.createStatement();
                int res = st.executeUpdate(sql);
                if (res > 0) {
                    JOptionPane.showMessageDialog(getRootPane(), "Mínimo vital actualizado");
                }
            } catch (SQLException | HeadlessException e) {
                JOptionPane.showMessageDialog(getRootPane(), e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(getRootPane(), "Ingrese monto mínimo");
            txt_pago_minimo.requestFocus();
        }
    }//GEN-LAST:event_btn_guardar_pagosActionPerformed

    private void txt_cambioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cambioKeyTyped
        int tecla = (int) evt.getKeyChar();
        if (tecla > 64 && tecla < 91 || tecla > 96 && tecla < 123)  {
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);
            JOptionPane.showMessageDialog(getRootPane(), "INGRESE SOLO NUMEROS");
            txt_cambio.requestFocus();
        }
    }//GEN-LAST:event_txt_cambioKeyTyped

    private void txt_igvKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_igvKeyTyped
        int tecla = (int) evt.getKeyChar();
        if (tecla > 64 && tecla < 91 || tecla > 96 && tecla < 123)  {
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);
            JOptionPane.showMessageDialog(getRootPane(), "INGRESE SOLO NUMEROS");
            txt_igv.requestFocus();
        }
        
//        Validar solo letras
//        int tecla = (int)evt.getKeyChar();
//        if(tecla>47 && tecla<58){
//            evt.setKeyChar((char)KeyEvent.VK_CLEAR);
//            JOptionPane.showMessageDialog(frm_nuevo.getRootPane(), "INGRESE SOLO LETRAS");
//            txt_nombres.requestFocus();
//            //txt_nombres.requestFocus();
//        }else{
//
//        }
    }//GEN-LAST:event_txt_igvKeyTyped

    private void txt_entradaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_entradaKeyTyped
        int tecla = (int) evt.getKeyChar();
        if (tecla > 64 && tecla < 91 || tecla > 96 && tecla < 123)  {
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);
            JOptionPane.showMessageDialog(getRootPane(), "INGRESE SOLO NUMEROS");
            txt_entrada.requestFocus();
        }
    }//GEN-LAST:event_txt_entradaKeyTyped

    private void txt_salidaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_salidaKeyTyped
        int tecla = (int) evt.getKeyChar();
        if (tecla > 64 && tecla < 91 || tecla > 96 && tecla < 123)  {
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);
            JOptionPane.showMessageDialog(getRootPane(), "INGRESE SOLO NUMEROS");
            txt_salida.requestFocus();
        }
    }//GEN-LAST:event_txt_salidaKeyTyped

    private void txt_pago_minimoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_pago_minimoKeyTyped
        int tecla = (int) evt.getKeyChar();
        if (tecla > 64 && tecla < 91 || tecla > 96 && tecla < 123)  {
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);
            JOptionPane.showMessageDialog(getRootPane(), "INGRESE SOLO NUMEROS");
            txt_pago_minimo.requestFocus();
        }
    }//GEN-LAST:event_txt_pago_minimoKeyTyped

    private void txt_telefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_telefonoKeyTyped
        int tecla = (int) evt.getKeyChar();
        if (tecla > 64 && tecla < 91 || tecla > 96 && tecla < 123)  {
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);
            JOptionPane.showMessageDialog(getRootPane(), "INGRESE SOLO NUMEROS");
            txt_telefono.requestFocus();
        }
    }//GEN-LAST:event_txt_telefonoKeyTyped

    private void txt_rucKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_rucKeyTyped
        int tecla = (int) evt.getKeyChar();
        if (tecla > 64 && tecla < 91 || tecla > 96 && tecla < 123)  {
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);
            JOptionPane.showMessageDialog(getRootPane(), "INGRESE SOLO NUMEROS");
            txt_ruc.requestFocus();
        }
    }//GEN-LAST:event_txt_rucKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Configuracion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_actualizar_anuncio;
    private javax.swing.JButton btn_actualizar_cambio;
    private javax.swing.JButton btn_actualizar_empresa;
    private javax.swing.JButton btn_actualizar_igv;
    private javax.swing.JButton btn_guardar_horarios;
    private javax.swing.JButton btn_guardar_pagos;
    private javax.swing.JCheckBox chx_modificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbl_fecha;
    private javax.swing.JTextArea txa_anuncios;
    private javax.swing.JTextField txt_cambio;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextField txt_entrada;
    private javax.swing.JTextField txt_igv;
    private javax.swing.JTextField txt_nom;
    private javax.swing.JTextField txt_pago_minimo;
    private javax.swing.JTextField txt_responsable;
    private javax.swing.JTextField txt_ruc;
    private javax.swing.JTextField txt_salida;
    private javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables
}
