/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Control.Conexion;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gaby
 */
public class Cruces extends javax.swing.JInternalFrame {

    DefaultTableModel model;
    Connection cc = new Conexion().conectar();

    public Cruces() {
        initComponents();
        titulos();
    }

    public void titulos() {
        String[] titulos = {"ID-ALMACEN", "ID-PRODUCTO", "CANTIDAD"};
        model = new DefaultTableModel(null, titulos);
        tblDatos.setModel(model);
    }

    public void buscarProductos(JTable tbl) throws Exception {
        limpiarTabla(tbl);
        String datos[] = new String[3];
        String sql = "select id_pro_medi, stock_pro_medi from tproducto_medicamento";
        try {
            Statement st = cc.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                datos[0] = "1";
                datos[1] = String.valueOf(rs.getInt("id_pro_medi"));
                datos[2] = rs.getString("stock_pro_medi");
                model.addRow(datos);
            }
            tbl.setModel(model);
            //tbl_productos.setModel(new DefaultTableModel());
        } catch (Exception e) {
            throw e;
        }
    }

    public void limpiarTabla(JTable tbl) {
        for (int i = 0; i < tbl.getRowCount(); i++) {
            model.removeRow(i);
            i -= 1;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        btnReg = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("CRUCES DE MERCADERIA");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblDatos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 600, -1));

        jButton3.setText("mostrarProductos");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        btnReg.setText("REGISTRAR EN TABLA PRODUCTOALMACEN");
        btnReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegActionPerformed(evt);
            }
        });
        getContentPane().add(btnReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 530, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            buscarProductos(tblDatos);
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegActionPerformed
        try {
            int numFilas = tblDatos.getRowCount();

            for (int i = 0; i < numFilas; i++) {
                int idAlmacen = Integer.parseInt(tblDatos.getValueAt(i, 0).toString());
                int idProducto = Integer.parseInt(tblDatos.getValueAt(i, 1).toString());
                int cantidad = Integer.parseInt(tblDatos.getValueAt(i, 2).toString());
                String sql = "INSERT INTO almacenproducto( idalmacen, idproducto, cantidad) VALUES ('" + idAlmacen + "','" + idProducto + "','" + cantidad + "')";
                Statement st = cc.createStatement();
                int res = st.executeUpdate(sql);
                if (res > 0) {
                    System.out.println("se registro el producto "+idProducto);

                }
            }
//            String sql = "INSERT INTO almacenproducto( idalmacen, idproducto, cantidad) VALUES ('" + p + "','" + privi + "')";
//            Statement st = cc.createStatement();
//            int res = st.executeUpdate(sql);
//            if (res > 0) {
//                JOptionPane.showMessageDialog(null, "PERFIL REGISTRADO");
//
//            } else {
//            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnRegActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReg;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDatos;
    // End of variables declaration//GEN-END:variables
}
