/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Control.Conexion;
import Control.ManejadorFechas;
import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gaby
 */
public final class Gastos extends javax.swing.JFrame {

    Connection con = new Conexion().conectar();
    int posx, posy;
    DefaultTableModel model_gastos;
    
    public Gastos() {
        setUndecorated(true);
        setAlwaysOnTop(true);
        initComponents();
        this.getContentPane().setBackground(Color.WHITE);
        setLocationRelativeTo(null);
        lbl_fecha.setText(""+new Fechas().fechaCadena());
        cabeceraTablaGastos();
    }
    
    
    public void cabeceraTablaGastos(){
        String titulos[] = {"NÚMERO","CONCEPTO","MONTO","FECHA"};
        model_gastos = new DefaultTableModel(null, titulos);
        tbl_gastos.setModel(model_gastos);
        bloquear();
        loadGastos();
        lbl_pie.setText(new Farma_inf().pie());
    }
    
    public void loadGastos(){
        String sql = "SELECT `id_gastos`, `descripcion_gasto`, `monto`, `fecha_gasto` FROM `tgastos` WHERE 1";
        try {
            String datos[] = new String[4];
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {                
                datos[0] = rs.getString("id_gastos");
                datos[1] = rs.getString("descripcion_gasto");
                datos[2] = rs.getString("monto");
                datos[3] = rs.getString("fecha_gasto");
                model_gastos.addRow(datos);
            }
            tbl_gastos.setModel(model_gastos);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(getRootPane(), e.getMessage());
        }
    }
    
    public void saveGastos(){
        String concepto = txt_concepto.getText();
        String fecha = new ManejadorFechas().getFechaActualMySQL();
        double monto = Double.parseDouble(txt_monto.getText());
        
        String sql = "INSERT INTO tgastos(`descripcion_gasto`, `monto`, `fecha_gasto`) VALUES ( '"+concepto+"', "+monto+", '"+fecha+"' )";
        try {
            Statement st = con.createStatement();
            int res = st.executeUpdate(sql);
            
            if (res>0) {
                JOptionPane.showMessageDialog(getRootPane(), "Gasto registrado");
            } else {
            }
        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(getRootPane(), e.getMessage());
        }
        
    }
    
    private void filaSeleccionada(){
        cmb_modificar.setEnabled(true);
        int fila = tbl_gastos.getSelectedRow();
        lbl_id.setText(tbl_gastos.getValueAt(fila, 0).toString());
        String concepto = tbl_gastos.getValueAt(fila, 1).toString();
        double monto = Double.parseDouble(tbl_gastos.getValueAt(fila, 2).toString());
        String fecha = tbl_gastos.getValueAt(fila, 3).toString();
        txt_modConcepto.setText(concepto);
        txt_modMonto.setText(""+monto);
    }
    
    public void bloquear(){
        cmb_modificar.setEnabled(false);
        txt_modConcepto.setEnabled(false);
        txt_modMonto.setEnabled(false);
        btn_save.setEnabled(false);
        jdc_fecha.setEnabled(false);
    }
    
    public void desbloquear(){
        cmb_modificar.setEnabled(true);
        txt_modConcepto.setEnabled(true);
        txt_modMonto.setEnabled(true);
        btn_save.setEnabled(true);
        jdc_fecha.setEnabled(true);
        txt_modConcepto.requestFocus();
    }
    
    private void limpiarCampos() {
        txt_concepto.setText("");
        txt_monto.setText("");
        txt_modConcepto.setText("");
        txt_modMonto.setText("");
        lbl_id.setText("...");
        txt_concepto.requestFocus();
    }
    
    public void limpiarTabla() {
        for (int i = 0; i < tbl_gastos.getRowCount(); i++) {
            model_gastos.removeRow(i);
            i -= 1;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_salir = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lbl_fecha = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_gastos = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        txt_monto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_concepto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btn_guardar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lbl_id = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_modMonto = new javax.swing.JTextField();
        txt_modConcepto = new javax.swing.JTextField();
        cmb_modificar = new javax.swing.JCheckBox();
        jdc_fecha = new com.toedter.calendar.JDateChooser();
        btn_save = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        panel_principal = new javax.swing.JPanel();
        panel_pie = new javax.swing.JPanel();
        lbl_pie = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_salir.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lbl_salir.setForeground(new java.awt.Color(255, 255, 255));
        lbl_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/logout.png"))); // NOI18N
        lbl_salir.setText("SALIR");
        lbl_salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_salirMouseClicked(evt);
            }
        });
        getContentPane().add(lbl_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Banner.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 60));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 620, 10));

        lbl_fecha.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lbl_fecha.setForeground(new java.awt.Color(0, 0, 102));
        lbl_fecha.setText("Viernes, 24 de Diciembre del 2015");
        getContentPane().add(lbl_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 140, -1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 620, 10));

        tbl_gastos.setForeground(new java.awt.Color(0, 51, 255));
        tbl_gastos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_gastos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_gastosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_gastos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 630, 260));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 102), 1, true), "REGISTRAR NUEVO GASTO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("SansSerif", 0, 14), new java.awt.Color(204, 0, 0))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_monto.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txt_monto.setForeground(new java.awt.Color(0, 51, 255));
        txt_monto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_monto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 204), 1, true));
        txt_monto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_montoActionPerformed(evt);
            }
        });
        txt_monto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_montoKeyTyped(evt);
            }
        });
        jPanel1.add(txt_monto, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 100, -1));

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("MONTO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, -1, -1));

        txt_concepto.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txt_concepto.setForeground(new java.awt.Color(0, 51, 255));
        txt_concepto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_concepto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 204), 1, true));
        txt_concepto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_conceptoActionPerformed(evt);
            }
        });
        jPanel1.add(txt_concepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 270, -1));

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setText("CONCEPTO");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        btn_guardar.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btn_guardar.setText("GUARDAR");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 120, -1));

        btn_cancelar.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btn_cancelar.setText("CANCELAR");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 630, 100));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 153), 1, true), "DATOS DE GASTO SELECCIONADO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("SansSerif", 0, 14), new java.awt.Color(255, 0, 0))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_id.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lbl_id.setForeground(new java.awt.Color(0, 51, 255));
        jPanel2.add(lbl_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 50, 30));

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setText("MONTO");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        txt_modMonto.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txt_modMonto.setForeground(new java.awt.Color(0, 51, 255));
        txt_modMonto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 204)));
        txt_modMonto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_modMontoKeyTyped(evt);
            }
        });
        jPanel2.add(txt_modMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 80, -1));

        txt_modConcepto.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txt_modConcepto.setForeground(new java.awt.Color(0, 51, 255));
        txt_modConcepto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 204)));
        txt_modConcepto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_modConceptoActionPerformed(evt);
            }
        });
        jPanel2.add(txt_modConcepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 210, -1));

        cmb_modificar.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        cmb_modificar.setForeground(new java.awt.Color(0, 0, 102));
        cmb_modificar.setText("MODIFICAR");
        cmb_modificar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 1, true));
        cmb_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_modificarActionPerformed(evt);
            }
        });
        jPanel2.add(cmb_modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, 110, 30));

        jdc_fecha.setDateFormatString("yyyy/MM/dd");
        jdc_fecha.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jPanel2.add(jdc_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 140, 30));

        btn_save.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btn_save.setText("GUARDAR");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });
        jPanel2.add(btn_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, 110, -1));

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 102));
        jLabel7.setText("CONCEPTO");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 102));
        jLabel8.setText("CODIGO");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 630, 130));

        panel_principal.setBackground(new java.awt.Color(255, 255, 255));
        panel_principal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 204), 2, true));
        getContentPane().add(panel_principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 650, 550));

        panel_pie.setBackground(new java.awt.Color(0, 102, 204));
        panel_pie.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_pie.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        lbl_pie.setForeground(new java.awt.Color(255, 255, 255));
        lbl_pie.setText("jLabel3");
        panel_pie.add(lbl_pie, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -1, 650, 30));

        getContentPane().add(panel_pie, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 610, 650, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        if (!txt_concepto.getText().trim().isEmpty()) {
            if (!txt_monto.getText().trim().isEmpty()) {
                saveGastos();
                limpiarTabla();
                loadGastos();
                limpiarCampos();
            } else {
                JOptionPane.showMessageDialog(getRootPane(), "Ingrese un monto de gasto");
            }
        } else {
            JOptionPane.showMessageDialog(getRootPane(), "Ingrese concepto de gasto");
        }
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void lbl_salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_salirMouseClicked
        dispose();
    }//GEN-LAST:event_lbl_salirMouseClicked

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        posx = evt.getX();
        posy = evt.getY();
    }//GEN-LAST:event_jLabel1MousePressed

    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
        Point point = MouseInfo.getPointerInfo().getLocation();
        this.setLocation(point.x-posx, point.y-posy);
    }//GEN-LAST:event_jLabel1MouseDragged

    private void cmb_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_modificarActionPerformed
        if (cmb_modificar.isSelected()) {
            desbloquear();
        } else {
            bloquear();
        }
    }//GEN-LAST:event_cmb_modificarActionPerformed

    private void tbl_gastosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_gastosMouseClicked
        filaSeleccionada();
        
    }//GEN-LAST:event_tbl_gastosMouseClicked

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        actualizarGasto();
    }//GEN-LAST:event_btn_saveActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        bloquear();
        tbl_gastos.clearSelection();
    }//GEN-LAST:event_formMouseClicked

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void txt_montoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_montoKeyTyped
        int tecla = (int) evt.getKeyChar();
        if (tecla > 64 && tecla < 91 || tecla > 96 && tecla < 123)  {
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);
            JOptionPane.showMessageDialog(getRootPane(), "INGRESE SOLO NUMEROS");
            txt_monto.requestFocus();
        }
    }//GEN-LAST:event_txt_montoKeyTyped

    private void txt_modMontoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_modMontoKeyTyped
        int tecla = (int) evt.getKeyChar();
        if (tecla > 64 && tecla < 91 || tecla > 96 && tecla < 123)  {
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);
            JOptionPane.showMessageDialog(getRootPane(), "INGRESE SOLO NUMEROS");
            txt_modMonto.requestFocus();
        }
    }//GEN-LAST:event_txt_modMontoKeyTyped

    private void txt_conceptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_conceptoActionPerformed
        txt_monto.requestFocus();
    }//GEN-LAST:event_txt_conceptoActionPerformed

    private void txt_montoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_montoActionPerformed
        btn_guardar.doClick();
    }//GEN-LAST:event_txt_montoActionPerformed

    private void txt_modConceptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_modConceptoActionPerformed
        txt_modMonto.requestFocus();
    }//GEN-LAST:event_txt_modConceptoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gastos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_save;
    private javax.swing.JCheckBox cmb_modificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private com.toedter.calendar.JDateChooser jdc_fecha;
    private javax.swing.JLabel lbl_fecha;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JLabel lbl_pie;
    private javax.swing.JLabel lbl_salir;
    private javax.swing.JPanel panel_pie;
    private javax.swing.JPanel panel_principal;
    private javax.swing.JTable tbl_gastos;
    private javax.swing.JTextField txt_concepto;
    private javax.swing.JTextField txt_modConcepto;
    private javax.swing.JTextField txt_modMonto;
    private javax.swing.JTextField txt_monto;
    // End of variables declaration//GEN-END:variables

    private void actualizarGasto() {
        try {
            int id = Integer.parseInt(lbl_id.getText());
            int fila = tbl_gastos.getSelectedRow();
            String concepto = txt_modConcepto.getText();
            double monto = Double.parseDouble(txt_modMonto.getText());
            String formato = jdc_fecha.getDateFormatString();
            Date date = jdc_fecha.getDate();
            SimpleDateFormat sdf = new SimpleDateFormat(formato);
            String fecha = sdf.format(date);
            String sql = "UPDATE `tgastos` SET `descripcion_gasto`='" + concepto + "',`monto`= " + monto + " ,`fecha_gasto`='" + fecha + "' WHERE `id_gastos`="+id+" ";

            Statement st = con.createStatement();
            int rs = st.executeUpdate(sql);
            
            if (rs>0) {
                JOptionPane.showMessageDialog(getRootPane(), "Gasto actualizado");
                limpiarTabla();
                loadGastos();
            } else {
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(getRootPane(), e.getMessage() + "\nIndique una fecha");
            
        }
        
    }
}
