/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Control.Conexion;

import Control.MyiReportVisor;
import Vista.Users;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.HashMap;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gaby
 */
public final class VentasxCliente extends javax.swing.JFrame {

    HashMap parametros = new HashMap();
    MyiReportVisor mrv;
    Connection con = new Conexion().conectar();
    DefaultTableModel model;
    public VentasxCliente() {
        initComponents();
        setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/IMG/icoono.jpg")).getImage());
        cargarTitulos();
        cargarTablaCliente();
        btn_reportes.setEnabled(false);
    }
    
    
    public void cargarTitulos(){
        String cabecera[] = {"ID","NOMBRE","APELLIDO","TELEFONO","DNI","SEXO","DIRECCION","EMAIL"};
        model = new DefaultTableModel(null, cabecera);
        tbl_clientes.setModel(model);
    }
    
    
    public void cargarTablaCliente(){
        String datos[] = new String[8];
        String sql = "SELECT `id_cli`,`nom_cli`, `apell_cli`, `telf_cli`, `dni_cli`, `sexo_cli`, `direc_cli`, `email_contac` FROM `tcliente` WHERE 1";
        try {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                datos[0] = rs.getString("id_cli");
                datos[1] = rs.getString("nom_cli");
                datos[2] = rs.getString("apell_cli");
                datos[3] = rs.getString("telf_cli");
                datos[4] = rs.getString("dni_cli");
                datos[5] = rs.getString("sexo_cli");
                datos[6] = rs.getString("direc_cli");
                datos[7] = rs.getString("email_contac");
                model.addRow(datos);
            }
            tbl_clientes.setModel(model);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
    
    public void clientePdf(int id){
        String datos[] = new String[7];
        String sql = "SELECT tcliente.nom_cli, tventa.id_venta, `fecha_venta`, `hora_venta`, `id_usu`, tcliente.id_cli, `id_caja` FROM `tventa` INNER JOIN tdetalleventa on tventa.id_venta = tdetalleventa.id_venta INNER JOIN tcliente on tventa.id_cli = tcliente.id_cli WHERE tcliente.id_cli ="+id+" ";
        
        try {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                datos[0] = rs.getString("tcliente.nom_cli");
                datos[1] = rs.getString("tcliente.nom_cli");
                datos[2] = rs.getString("tcliente.nom_cli");
                datos[3] = rs.getString("tcliente.nom_cli");
                datos[4] = rs.getString("tcliente.nom_cli");
                datos[5] = rs.getString("tcliente.nom_cli");
                datos[6] = rs.getString("tcliente.nom_cli");
                datos[7] = rs.getString("tcliente.nom_cli");
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_clientes = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btn_reportes = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_clientes.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        tbl_clientes.setForeground(new java.awt.Color(0, 51, 255));
        tbl_clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_clientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_clientes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 730, 330));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 255), 2, true));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_reportes.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btn_reportes.setText("CREAR REPORTE");
        btn_reportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reportesActionPerformed(evt);
            }
        });
        jPanel1.add(btn_reportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, -1, -1));

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("SELECCIONAR CLIENTE");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 102, 255));
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 760, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/1453329666_people.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 50, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 760, 470));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Banner.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_reportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reportesActionPerformed
        int fila = tbl_clientes.getSelectedRow();
        int id = Integer.parseInt(tbl_clientes.getValueAt(fila, 0).toString());
        String n= new Users().getCustomerName(id);
        String a = new Users().getCustomerLastName(id);
        String nombre = n+" "+a;
        parametros.put("nombre", nombre);
        parametros.put("id_cliente", id);
        mrv = new MyiReportVisor(System.getProperty("user.dir")+"\\reportes\\ventasCliente.jrxml", parametros);
        mrv.exportarAPdf();
    }//GEN-LAST:event_btn_reportesActionPerformed

    private void tbl_clientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_clientesMouseClicked
        int fila = tbl_clientes.getSelectedRow();
        int id = Integer.parseInt(tbl_clientes.getValueAt(fila, 0).toString());
        if (fila>=0) {
            btn_reportes.setEnabled(true);
        } else {
            btn_reportes.setEnabled(false);
        }
    }//GEN-LAST:event_tbl_clientesMouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        btn_reportes.setEnabled(false);
    }//GEN-LAST:event_jPanel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentasxCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentasxCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentasxCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentasxCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentasxCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_reportes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_clientes;
    // End of variables declaration//GEN-END:variables
}
