

package LOGIN;

import java.awt.Color;

/**
 *
 * @author Goby
 */
public class Bienvenido extends javax.swing.JFrame {
    private int auxiliar = 0;
    private boolean realizado = false;
    hilo h = new hilo();

    /**
     * Creates new form Bienvenido
     */
    public Bienvenido() {
        initComponents();
        Bienvenido.this.getRootPane().setOpaque(false);//para que no se vea nada
        Bienvenido.this.getContentPane().setBackground(new Color (0,0,0,0));//establece color rgb y por ultimo transparencia
        Bienvenido.this.setBackground(new Color (0,0,0,0));//
        this.setResizable(false);//hace que el programa no se pueda redimensionar     
        setLocation(400, 400);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_texto = new javax.swing.JLabel();
        barra = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_texto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_texto.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lbl_texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 170, 30));

        barra.setBorder(null);
        getContentPane().add(barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 640, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/LogoFarmacia.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        if (realizado==false) {
            realizado = true;
            barra.setMaximum(49);
            barra.setMinimum(0);
            barra.setStringPainted(true);
            h.start();
        }
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bienvenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bienvenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bienvenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bienvenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bienvenido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_texto;
    // End of variables declaration//GEN-END:variables
private class hilo extends Thread {

        @Override
        public void run() {
            try {
                while (true) {
                    auxiliar++;
                    barra.setValue(auxiliar);
                    repaint();
                    switch (auxiliar) {
                        case 0:
                            lbl_texto.setText("Cargando programa....");
                            break;
                        case 10:
                            lbl_texto.setText("Leyendo preferencias....");
                            break;
                        case 20:
                            lbl_texto.setText("Cargando módulos....");
                            break;
                        case 30:
                            lbl_texto.setText("Verificando sesiones....");
                            break;
                        case 40:
                            lbl_texto.setText("Carga finalizada....");
                            break;
                        case 50:
                            Login p = new Login() ;
                            p.setVisible(true);
                            p.setLocationRelativeTo(null);
                            Bienvenido.this.dispose();
                            break;
                    }
                    Thread.sleep(15);
                }

            } catch (Exception e) {
            }

        }
    }


}


