/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package farmacia;

import Control.MyiReportVisor;
import LOGIN.Login;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import Vista.*;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Adolfo
 */
public class Principal_administrador extends javax.swing.JFrame {

    MyiReportVisor mrv;
    HashMap parametros = new HashMap();

    public Principal_administrador() {
        //setUndecorated(true);
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        setTitle("ADMINISTRACION");
        setIconImage(new ImageIcon(getClass().getResource("/IMG/icoono.jpg")).getImage());
        ((JPanel)getContentPane()).setOpaque(true);
        new Farma_inf().alertaProductos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jButton1 = new javax.swing.JButton();
        btn_usuarios = new javax.swing.JButton();
        btn_proveedores = new javax.swing.JButton();
        btn_tiendas = new javax.swing.JButton();
        btn_gastos = new javax.swing.JButton();
        btn_stock = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btn_compras = new javax.swing.JButton();
        btn_productos = new javax.swing.JButton();
        btn_clientes = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lbl_id = new javax.swing.JLabel();
        lbl_user = new javax.swing.JLabel();
        txt_usu = new javax.swing.JTextField();
        txt_id = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        m_sistema = new javax.swing.JMenu();
        m_config = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        m_cerar_sesion = new javax.swing.JMenuItem();
        m_salir = new javax.swing.JMenuItem();
        m_registros = new javax.swing.JMenu();
        m_clientes = new javax.swing.JMenuItem();
        m_empleados = new javax.swing.JMenuItem();
        m_proveedor = new javax.swing.JMenuItem();
        m_contactos = new javax.swing.JMenuItem();
        m_productos = new javax.swing.JMenuItem();
        m_gastos = new javax.swing.JMenuItem();
        m_compras = new javax.swing.JMenuItem();
        m_stock_productos = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        m_reportes = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        m_cata_clientes = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        item_enero = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1920, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 880, Short.MAX_VALUE)
        );

        getContentPane().add(escritorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 1920, 880));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/1454973695_sign-up.png"))); // NOI18N
        jButton1.setText("ASISTENCIA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 130, 70));

        btn_usuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/folder_who.png"))); // NOI18N
        btn_usuarios.setText("USUARIOS");
        btn_usuarios.setEnabled(false);
        btn_usuarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_usuarios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_usuariosActionPerformed(evt);
            }
        });
        getContentPane().add(btn_usuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 130, 70));

        btn_proveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/1453295253_provider.png"))); // NOI18N
        btn_proveedores.setText("PROVEEDORES");
        btn_proveedores.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_proveedores.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_proveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_proveedoresActionPerformed(evt);
            }
        });
        getContentPane().add(btn_proveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 130, 70));

        btn_tiendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/1453296051_09.png"))); // NOI18N
        btn_tiendas.setText("LABORATORIOS");
        btn_tiendas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_tiendas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_tiendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tiendasActionPerformed(evt);
            }
        });
        getContentPane().add(btn_tiendas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 130, 70));

        btn_gastos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/1453296836_Cash_register.png"))); // NOI18N
        btn_gastos.setText("GASTOS");
        btn_gastos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_gastos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_gastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gastosActionPerformed(evt);
            }
        });
        getContentPane().add(btn_gastos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 130, 70));

        btn_stock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/1453297006_20.png"))); // NOI18N
        btn_stock.setText("STOCK");
        btn_stock.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_stock.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_stockActionPerformed(evt);
            }
        });
        getContentPane().add(btn_stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 130, 70));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/1461702483_sales_bag_shopping_bargain_retail.png"))); // NOI18N
        jButton2.setText("VENTAS");
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 130, 70));

        btn_compras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/1453297151_empty-shopping-cart.png"))); // NOI18N
        btn_compras.setText("COMPRAS");
        btn_compras.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_compras.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_compras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_comprasActionPerformed(evt);
            }
        });
        getContentPane().add(btn_compras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, 130, 70));

        btn_productos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/1453295875_packing.png"))); // NOI18N
        btn_productos.setText("PRODUCTOS");
        btn_productos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_productos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_productosActionPerformed(evt);
            }
        });
        getContentPane().add(btn_productos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 130, 70));

        btn_clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/clientes.png"))); // NOI18N
        btn_clientes.setText("  CLIENTES");
        btn_clientes.setToolTipText("");
        btn_clientes.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_clientes.setBorderPainted(false);
        btn_clientes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_clientes.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btn_clientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_clientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clientesActionPerformed(evt);
            }
        });
        getContentPane().add(btn_clientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 130, 70));
        btn_clientes.getAccessibleContext().setAccessibleName("CLIENTES");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_id.setText("ID");
        jPanel1.add(lbl_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        lbl_user.setText("USUARIO");
        jPanel1.add(lbl_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, -1, -1));

        txt_usu.setEditable(false);
        txt_usu.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txt_usu, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 140, -1));

        txt_id.setEditable(false);
        txt_id.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 130, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 5, 420, 40));

        m_sistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Monitor-icon.png"))); // NOI18N
        m_sistema.setText("SISTEMA");
        m_sistema.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N

        m_config.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        m_config.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/1453101097_Wrench.png"))); // NOI18N
        m_config.setText("CONFIGURACIÓN");
        m_config.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_configActionPerformed(evt);
            }
        });
        m_sistema.add(m_config);

        jMenuItem20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/1453285788_catalog.png"))); // NOI18N
        jMenuItem20.setText("KARDEX");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        m_sistema.add(jMenuItem20);

        jMenuItem17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/1453415037_calendar.png"))); // NOI18N
        jMenuItem17.setText("CADUCIDAD DE PRODUCTOS");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        m_sistema.add(jMenuItem17);

        m_cerar_sesion.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        m_cerar_sesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/logout.png"))); // NOI18N
        m_cerar_sesion.setText("CERRAR SESIÓN");
        m_cerar_sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_cerar_sesionActionPerformed(evt);
            }
        });
        m_sistema.add(m_cerar_sesion);

        m_salir.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        m_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/exit.png"))); // NOI18N
        m_salir.setText("SALIR");
        m_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_salirActionPerformed(evt);
            }
        });
        m_sistema.add(m_salir);

        jMenuBar1.add(m_sistema);

        m_registros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/1453328127_accessories-text-editor.png"))); // NOI18N
        m_registros.setText("REGISTROS");
        m_registros.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N

        m_clientes.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        m_clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/1453103738_customers.png"))); // NOI18N
        m_clientes.setText("REGISTRAR CLIENTES");
        m_clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_clientesActionPerformed(evt);
            }
        });
        m_registros.add(m_clientes);

        m_empleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/1453103927_customers.png"))); // NOI18N
        m_empleados.setText("REGISTRAR EMPLEADOS");
        m_empleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_empleadosActionPerformed(evt);
            }
        });
        m_registros.add(m_empleados);

        m_proveedor.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        m_proveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/1453104151_provider.png"))); // NOI18N
        m_proveedor.setText("REGISTRAR PROVEEDOR");
        m_proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_proveedorActionPerformed(evt);
            }
        });
        m_registros.add(m_proveedor);

        m_contactos.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        m_contactos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icon_m.png"))); // NOI18N
        m_contactos.setText("REGISTRAR PAGOS");
        m_contactos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_contactosActionPerformed(evt);
            }
        });
        m_registros.add(m_contactos);

        m_productos.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        m_productos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/1453242429_chemistry_reaction_product.png"))); // NOI18N
        m_productos.setText("REGISTRAR PRODUCTOS");
        m_productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_productosActionPerformed(evt);
            }
        });
        m_registros.add(m_productos);

        m_gastos.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        m_gastos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/1453243072_cash_register.png"))); // NOI18N
        m_gastos.setText("REGISTRAR GASTOS");
        m_gastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_gastosActionPerformed(evt);
            }
        });
        m_registros.add(m_gastos);

        m_compras.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        m_compras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/1453244507_shopping-edit.png"))); // NOI18N
        m_compras.setText("REGISTRAR COMPRAS");
        m_compras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_comprasActionPerformed(evt);
            }
        });
        m_registros.add(m_compras);

        m_stock_productos.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        m_stock_productos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/1453244908_20.png"))); // NOI18N
        m_stock_productos.setText("VER STOCK PRODUCTOS");
        m_stock_productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_stock_productosActionPerformed(evt);
            }
        });
        m_registros.add(m_stock_productos);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/1453287637_clipboard-charts.png"))); // NOI18N
        jMenuItem1.setText("GESTIÓN DE VENTAS");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        m_registros.add(jMenuItem1);

        jMenuItem18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/1453286780_Sales-by-Payment-Method-rep.png"))); // NOI18N
        jMenuItem18.setText("GESTIÓN DE COMPRAS");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        m_registros.add(jMenuItem18);

        jMenuItem22.setText("REGISTRAR ALMACEN");
        jMenuItem22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem22ActionPerformed(evt);
            }
        });
        m_registros.add(jMenuItem22);

        jMenuItem24.setText("MOVIMIENTOS ALMACEN");
        jMenuItem24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem24ActionPerformed(evt);
            }
        });
        m_registros.add(jMenuItem24);

        jMenuBar1.add(m_registros);

        m_reportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/1453328195_gnome-mime-application-vnd.lotus-1-2-3.png"))); // NOI18N
        m_reportes.setText("REPORTES");
        m_reportes.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/1453103738_customers.png"))); // NOI18N
        jMenu4.setText("CLIENTES");

        m_cata_clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/1453245109_distributor-report.png"))); // NOI18N
        m_cata_clientes.setText("CATALOGO CLIENTES");
        m_cata_clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_cata_clientesActionPerformed(evt);
            }
        });
        jMenu4.add(m_cata_clientes);

        jMenuItem14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/1453245237_sales-report.png"))); // NOI18N
        jMenuItem14.setText("VENTAS POR CLIENTE");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem14);

        m_reportes.add(jMenu4);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/1453104151_provider.png"))); // NOI18N
        jMenu5.setText("PROVEEDORES");

        jMenuItem15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/1453245690_reports.png"))); // NOI18N
        jMenuItem15.setText("CATALOGO PROVEEDORES");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem15);

        jMenuItem16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/1453285028_shopping.png"))); // NOI18N
        jMenuItem16.setText("COMPRAS POR PROVEEDOR");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem16);

        m_reportes.add(jMenu5);

        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/1453103927_customers.png"))); // NOI18N
        jMenu8.setText("VENDEDORES");

        jMenuItem21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/1453287512_sales-report.png"))); // NOI18N
        jMenuItem21.setText("VENTAS POR VENDEDOR");
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem21ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem21);

        m_reportes.add(jMenu8);

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/1453245455_money_bag.png"))); // NOI18N
        jMenu7.setText("VENTAS");

        jMenuItem19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/1453286780_Sales-by-Payment-Method-rep.png"))); // NOI18N
        jMenuItem19.setText("VENTAS POR DÍA");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem19);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/1453286876_sales-report.png"))); // NOI18N
        jMenu1.setText("VENTAS POR MES");

        item_enero.setText("ENERO");
        item_enero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_eneroActionPerformed(evt);
            }
        });
        jMenu1.add(item_enero);

        jMenuItem3.setText("FEBRERO");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("MARZO");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setText("ABRIL");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem6.setText("MAYO");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuItem7.setText("JUNIO");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenuItem8.setText("JULIO");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem8);

        jMenuItem9.setText("AGOSTO");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem9);

        jMenuItem10.setText("SETIEMBRE");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem10);

        jMenuItem11.setText("OCTUBRE");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem11);

        jMenuItem12.setText("NOVIEMBRE");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem12);

        jMenuItem13.setText("DICIEMBRE");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem13);

        jMenu7.add(jMenu1);

        m_reportes.add(jMenu7);

        jMenu9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/1453243072_cash_register.png"))); // NOI18N
        jMenu9.setText("COMPRAS");

        jMenuItem23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/1453289091_money.png"))); // NOI18N
        jMenuItem23.setText("REPORTE DE COMPRAS");
        jMenuItem23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem23ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem23);

        m_reportes.add(jMenu9);

        jMenuBar1.add(m_reportes);

        jMenu2.setText("AYUDA");

        jMenuItem2.setText("ACERCA  DE");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void m_configActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_configActionPerformed
           new Configuracion().setVisible(true);
    }//GEN-LAST:event_m_configActionPerformed

    private void m_empleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_empleadosActionPerformed
       Reg_usuario ru = new Reg_usuario();
       ru.setVisible(true);
    }//GEN-LAST:event_m_empleadosActionPerformed

    private void m_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_salirActionPerformed
       
       this.dispose();
       
    }//GEN-LAST:event_m_salirActionPerformed

    private void m_cerar_sesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_cerar_sesionActionPerformed
        Login l = new Login();
        this.dispose();
        l.setVisible(true);
    }//GEN-LAST:event_m_cerar_sesionActionPerformed

    private void m_clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_clientesActionPerformed
       Reg_cliente rc = new Reg_cliente();
       rc.setVisible(true);
    }//GEN-LAST:event_m_clientesActionPerformed

    private void m_stock_productosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_stock_productosActionPerformed
       new Stock().setVisible(true);
    }//GEN-LAST:event_m_stock_productosActionPerformed

    private void btn_clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clientesActionPerformed
       Reg_cliente rc = new Reg_cliente();
       rc.setVisible(true);
    }//GEN-LAST:event_btn_clientesActionPerformed

    private void m_productosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_productosActionPerformed
        Reg_producto rp = new Reg_producto();
        rp.setVisible(true);
    }//GEN-LAST:event_m_productosActionPerformed

    private void btn_tiendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tiendasActionPerformed
        try {
            new Laboratorios().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Principal_administrador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_tiendasActionPerformed

    private void btn_gastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gastosActionPerformed
       Gastos g = new Gastos();
       g.setVisible(true);
    }//GEN-LAST:event_btn_gastosActionPerformed

    private void btn_stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_stockActionPerformed
        Stock st = new Stock();
        st.setVisible(true);
    }//GEN-LAST:event_btn_stockActionPerformed

    private void btn_comprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_comprasActionPerformed
        Compras c = new Compras();
        c.setVisible(true);
    }//GEN-LAST:event_btn_comprasActionPerformed

    private void btn_proveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_proveedoresActionPerformed
        Reg_proveedor rp =new Reg_proveedor();
        rp.setVisible(true);
    }//GEN-LAST:event_btn_proveedoresActionPerformed

    private void m_proveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_proveedorActionPerformed
      Reg_proveedor rp = new Reg_proveedor();
      rp.setVisible(true);
              
    }//GEN-LAST:event_m_proveedorActionPerformed

    private void m_comprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_comprasActionPerformed
      new Compras().setVisible(true);
    }//GEN-LAST:event_m_comprasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       new Asistencias().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void m_contactosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_contactosActionPerformed
        new Pagos().setVisible(true);
    }//GEN-LAST:event_m_contactosActionPerformed

    private void m_cata_clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_cata_clientesActionPerformed
        mrv = new MyiReportVisor(System.getProperty("user.dir")+"\\reportes\\rep_clientes.jrxml", parametros);
        mrv.exportarAPdf();
    }//GEN-LAST:event_m_cata_clientesActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        new VentasxCliente().setVisible(true);
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        mrv = new MyiReportVisor(System.getProperty("user.dir")+"\\reportes\\provList.jrxml", parametros);
        mrv.exportarAPdf();
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        new ComprasxProveedor().setVisible(true);
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        new Flujo_caja().setVisible(true);
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void item_eneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_eneroActionPerformed
        mrv = new MyiReportVisor(System.getProperty("user.dir")+"\\reportes\\ventasenero.jrxml", parametros);
        mrv.exportarAPdf();
    }//GEN-LAST:event_item_eneroActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        mrv = new MyiReportVisor(System.getProperty("user.dir")+"\\reportes\\ventasfebrero.jrxml", parametros);
        mrv.exportarAPdf();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        mrv = new MyiReportVisor(System.getProperty("user.dir")+"\\reportes\\ventasmarzo.jrxml", parametros);
        mrv.exportarAPdf();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        mrv = new MyiReportVisor(System.getProperty("user.dir")+"\\reportes\\ventasabril.jrxml", parametros);
        mrv.exportarAPdf();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        mrv = new MyiReportVisor(System.getProperty("user.dir")+"\\reportes\\ventasmayo.jrxml", parametros);
        mrv.exportarAPdf();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        mrv = new MyiReportVisor(System.getProperty("user.dir")+"\\reportes\\ventasjunio.jrxml", parametros);
        mrv.exportarAPdf();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        mrv = new MyiReportVisor(System.getProperty("user.dir")+"\\reportes\\ventasjulio.jrxml", parametros);
        mrv.exportarAPdf();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        mrv = new MyiReportVisor(System.getProperty("user.dir")+"\\reportes\\ventasagosto.jrxml", parametros);
        mrv.exportarAPdf();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        mrv = new MyiReportVisor(System.getProperty("user.dir")+"\\reportes\\ventassetiembre.jrxml", parametros);
        mrv.exportarAPdf();
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        mrv = new MyiReportVisor(System.getProperty("user.dir")+"\\src\\Reportes\\ventasoctubre.jrxml", parametros);
        mrv.exportarAPdf();
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        mrv = new MyiReportVisor(System.getProperty("user.dir")+"\\reportes\\ventasnoviembre.jrxml", parametros);
        mrv.exportarAPdf();
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        mrv = new MyiReportVisor(System.getProperty("user.dir")+"\\reportes\\ventasdiciembre.jrxml", parametros);
        mrv.exportarAPdf();
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void m_gastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_gastosActionPerformed
       new Gastos().setVisible(true);
    }//GEN-LAST:event_m_gastosActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        new Ayuda().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        new Caducidad_productos().setVisible(true);
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem21ActionPerformed
        new VentasUsuario().setVisible(true);
    }//GEN-LAST:event_jMenuItem21ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      Ventas v = new Ventas();
        int id = Integer.parseInt(txt_id.getText());
        String usuario = txt_usu.getText();
        v.txt_usuario.setText(usuario);
        v.txt_codigo.setText(""+id);
        v.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new gestionVentas().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        new gestionCompras().setVisible(true);
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        new Kardex().setVisible(true);
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void btn_productosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_productosActionPerformed
        Reg_productoAdmin rpa = new Reg_productoAdmin();
        rpa.setVisible(true);
    }//GEN-LAST:event_btn_productosActionPerformed

    private void btn_usuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_usuariosActionPerformed
        Reg_usuario ru = new Reg_usuario();
        ru.setVisible(true);
    }//GEN-LAST:event_btn_usuariosActionPerformed

    private void jMenuItem23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem23ActionPerformed
        new ReporteDeCompras().setVisible(true);
    }//GEN-LAST:event_jMenuItem23ActionPerformed

    private void jMenuItem22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem22ActionPerformed
        try {
            Almacenes a = new Almacenes();
            escritorio.add(a);
            a.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Principal_administrador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem22ActionPerformed

    private void jMenuItem24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem24ActionPerformed
        try {
            GestionAlmacen ga = new GestionAlmacen();
            escritorio.add(ga);
            ga.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(Principal_administrador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem24ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal_administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal_administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal_administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal_administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal_administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clientes;
    private javax.swing.JButton btn_compras;
    private javax.swing.JButton btn_gastos;
    private javax.swing.JButton btn_productos;
    private javax.swing.JButton btn_proveedores;
    private javax.swing.JButton btn_stock;
    private javax.swing.JButton btn_tiendas;
    private javax.swing.JButton btn_usuarios;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuItem item_enero;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel lbl_id;
    public javax.swing.JLabel lbl_user;
    private javax.swing.JMenuItem m_cata_clientes;
    private javax.swing.JMenuItem m_cerar_sesion;
    private javax.swing.JMenuItem m_clientes;
    private javax.swing.JMenuItem m_compras;
    private javax.swing.JMenuItem m_config;
    private javax.swing.JMenuItem m_contactos;
    private javax.swing.JMenuItem m_empleados;
    private javax.swing.JMenuItem m_gastos;
    private javax.swing.JMenuItem m_productos;
    private javax.swing.JMenuItem m_proveedor;
    private javax.swing.JMenu m_registros;
    private javax.swing.JMenu m_reportes;
    private javax.swing.JMenuItem m_salir;
    private javax.swing.JMenu m_sistema;
    private javax.swing.JMenuItem m_stock_productos;
    public javax.swing.JTextField txt_id;
    public javax.swing.JTextField txt_usu;
    // End of variables declaration//GEN-END:variables
}
