/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package farmacia;

import Control.Conexion;
import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.MouseInfo;
import java.awt.Point;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Adolfo
 */
public class Reg_perfil extends javax.swing.JFrame {
     int posx, posy;
    
    
Connection con = new Conexion().conectar();
String privi= null;
   
    public Reg_perfil() {
        setUndecorated(true);
        initComponents();
        setAlwaysOnTop(true);
        setLocationRelativeTo(this);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel28 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_perfil = new javax.swing.JTextField();
        btn_guardar_perfil = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        chx_total = new javax.swing.JCheckBox();
        chx_limitado = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/logout.png"))); // NOI18N
        jLabel28.setText("SALIR");
        jLabel28.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel28.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel28MouseDragged(evt);
            }
        });
        jLabel28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel28MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel28MousePressed(evt);
            }
        });
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Banner.png"))); // NOI18N
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -7, 397, 70));

        jLabel2.setText("NOMBRE PERFIL");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 127, -1, -1));
        getContentPane().add(txt_perfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 125, 218, -1));

        btn_guardar_perfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/1449532190_3floppy_unmount.png"))); // NOI18N
        btn_guardar_perfil.setText("GUARDAR");
        btn_guardar_perfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardar_perfilActionPerformed(evt);
            }
        });
        getContentPane().add(btn_guardar_perfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 217, -1, 48));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/1454106190_Login Manager.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 69, -1, -1));

        jLabel4.setText("PRIVILEGIOS");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 167, 78, -1));

        chx_total.setText("TOTAL");
        chx_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chx_totalActionPerformed(evt);
            }
        });
        getContentPane().add(chx_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 163, -1, -1));

        chx_limitado.setText("LIMITADO");
        chx_limitado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chx_limitadoActionPerformed(evt);
            }
        });
        getContentPane().add(chx_limitado, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 163, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chx_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chx_totalActionPerformed
        if (chx_total.isSelected()) {
            chx_total.setForeground(Color.green);
            chx_limitado.setForeground(Color.RED);
            chx_limitado.setEnabled(false);
            privi = "TOTAL";
            
        } else {
            chx_total.setForeground(Color.black);
            chx_limitado.setForeground(Color.black);
            chx_limitado.setEnabled(true);
        }
    }//GEN-LAST:event_chx_totalActionPerformed

    private void chx_limitadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chx_limitadoActionPerformed
       if (chx_limitado.isSelected()) {
            chx_limitado.setForeground(Color.green);
            chx_total.setForeground(Color.RED);
            chx_total.setEnabled(false);
            privi ="LIMITADO";
        } else {
            chx_limitado.setForeground(Color.black);
            chx_total.setForeground(Color.black);
            chx_total.setEnabled(true);
        }
    }//GEN-LAST:event_chx_limitadoActionPerformed

    private void btn_guardar_perfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardar_perfilActionPerformed
        String p = txt_perfil.getText();
        
        String sql = "INSERT INTO tperfil( descrip_perfil, priv_perfil) VALUES ('"+p+"','"+privi+"')";
        try {
            Statement st = con.createStatement();
            int res = st.executeUpdate(sql);
            if (res > 0 ) {
                JOptionPane.showMessageDialog(null, "PERFIL REGISTRADO");
                
            } else {
            }
            
        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
    }//GEN-LAST:event_btn_guardar_perfilActionPerformed

    private void jLabel28MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseDragged

    }//GEN-LAST:event_jLabel28MouseDragged

    private void jLabel28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel28MouseClicked

    private void jLabel28MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MousePressed

    }//GEN-LAST:event_jLabel28MousePressed

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
         posx = evt.getX();
         posy = evt.getY();
    }//GEN-LAST:event_jLabel1MousePressed

    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
       Point point = MouseInfo.getPointerInfo().getLocation();
       this.setLocation(point.x-posx, point.y-posy);
    }//GEN-LAST:event_jLabel1MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reg_perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reg_perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reg_perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reg_perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reg_perfil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_guardar_perfil;
    private javax.swing.JCheckBox chx_limitado;
    private javax.swing.JCheckBox chx_total;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txt_perfil;
    // End of variables declaration//GEN-END:variables
}
